baseURL = "http://ealondon.com/"
languageCode = "en-gb"
title = "EA London"
theme = "local-ea-template"

[params]
  fullTitle = "Effective Altruism London"
  strapline = "Helping you do good better"
  firstButtonText = "Get updates"
  firstButtonLink = "http://ealondon.us5.list-manage.com/subscribe/post?u=7438f1bb80988376e9cae8c11&id=182579324a&SOURCE=Homepage&OPTIN=True&SUBREASON=you%20signed%20up%20to%20this%20list%20on%20the%20EA%20London%20website."
  secondButtonText = "Join us on Facebook"
  secondButtonLink = "https://www.facebook.com/groups/EALondon/"
