# baseURL should be
# "https://YOUR-GITHUB-USERNAME.github.io/lean-site-template/" during development,
# and "your-ea-domain.org/" after your domain has been set up.
baseURL = "www.altruismi.fi"
theme = "local-ea-template"
canonifyURLs = true

# If you are using multiple languages and want a different default,
# you can change this language code. In this particular case,
# baseURL will be the English site, and baseURL/<language code> will be the
# other languages.
DefaultContentLanguage = "fi"

# These params are used by the local EA Hugo template
# used to generate the site. You can find the template
# at https://github.com/rtcharity/local-ea-template.
  [params]

  [Languages]
  [Languages.en]
  title = "EA Helsinki"
  weight = 1
  languageCode = "en"

  [Languages.en.general]
  ## -- GENERAL SITE PARAMETERS -- ##
  fullTitle = "Effective Altruism Helsinki"
  strapline = "Helping you do good better"

  [Languages.en.groupinfo]
  ## -- EA GROUP INFO -- ##
  legalOrgName = "Effective Altruism Helsinki"
  orgLocations = "Helsinki"
  contactEmail = "helsinki@altruismi.fi"

  [Languages.en.navbar]
  ## -- NAVIGATION BAR HEADERS -- ##
  # You probably don't need/want to change these,
  # but if you do you'll also want to change the relevant .md file under the
  # content folder so the copy corresponds with the header.
  home = "Home"
  effectiveAltruism = "More Resources"
  aboutEA = "Effective Altruism"
  readingMaterial = "Reading Material"
  keyTerms = "Key Terms"
  organizations = "Organizations"
  contact= "Contact"

  [Languages.en.pages]
  ## -- PAGE HEADERS -- ##
  contactPageHeader = "Contact us"
  aboutEAPageHeader = "What is Effective Altruism?"

  [Languages.en.homepage]
   ## -- HOMEPAGE -- ##
  topBannerText = "Who are we?"
  leadText = "We're a group of people who want to help you answer the question: how can I do good better?"
  firstSectionHeader = "Doing good better"
  secondSectionHeader = "Building a community"
  thirdSectionHeader = "Finding better ways to help"
  # bottomBannerText = "A proud member of the effective altruism network"

  [Languages.en.contactform]
  ## -- CONTACT FORM -- ##
  leadText = "Say hi!"
  senderName = "Your name (required)"
  senderEmail = "Your email (required)"
  emailSubject = "Subject"
  emailMessage = "Your Message"
  send = "Send"

  [Languages.en.jumbotron]
  # These are the buttons right under the header that appears on the main page.
  # You can use them to link to a mailing list or Facebook page.
  # Make sure the links start with http:// or https://
  firstButtonLink = "https://www.facebook.com/EffectiveAltruismHY/"
  firstButtonText = "Check us out on Facebook"
  secondButtonText = "Contact Us"
  secondButtonLink = "https://oaarne.github.io/lean-site-template/contact/"
  # Remove the # before the text to add the optional Meetup button
  # meetupButtonText = "Find us on Meetup"

  [Languages.en.urls]
  ## -- EA GROUP FB/TWITTER/MEETUP URLS -- ##
  # If your group does not have URLs for these, just add # before the line
  # to remove the link from the site
  facebookUrl = "https://www.facebook.com/EffectiveAltruismHY/"
  # twitterUrl = ""
  # meetupUrl = ""

  [Languages.fi]
  languageCode = "fi"
  title = "EA Helsinki"
  weight = 2

  [Languages.fi.general]
  ## -- GENERAL SITE PARAMETERS -- ##
  fullTitle = "Effective Altruism Helsinki"
  strapline = "Autamme sinua tekemään hyvää paremmin."

  [Languages.fi.groupinfo]
  ## -- EA GROUP INFO -- ##
  legalOrgName = "Effective Altruism Helsinki"
  orgLocations = "Helsinki"
  contactEmail = "helsinki@altruismi.fi"

  [Languages.fi.navbar]
  ## -- NAVIGATION BAR HEADERS -- ##
  # You probably don't need/want to change these,
  # but if you do you'll also want to change the relevant .md file under the
  # content folder so the copy corresponds with the header.
  home = "Etusivu"
  # effectiveAltruism = "Efektiivinen altruismi"
  aboutEA = "Mitä on efektiivinen altruismi?"
  # readingMaterial = "Luettavaa"
  # keyTerms = "Keskeisiä käsitteitä"
  # organizations = "Organisaatioita"
  contact= "Ota yhteyttä"

  [Languages.fi.pages]
  ## -- PAGE HEADERS -- ##
  contactPageHeader = "Ota yhteyttä"
  aboutEAPageHeader = "Mitä on efektiivinen altruismi?"

  [Languages.fi.homepage]
   ## -- HOMEPAGE -- ##
  topBannerText = "Keitä me olemme?"
  leadText = "Olemme yhteisö, joka pyrkii auttamaan toisiaan vastaamaan kysymykseen: Miten voin tehdä hyvää paremmin?"
  firstSectionHeader = "Hyvän tekeminen, paremmin"
  secondSectionHeader = "Liity yhteisömme"
  thirdSectionHeader = "Etsimme parhaita tapoja tehdä hyvää"
  bottomBannerText = ""

  [Languages.fi.contactform]
  ## -- CONTACT FORM -- ##
  leadText = "Sano hei!"
  senderName = "Nimesi (pakollinen)"
  senderEmail = "Sähköpostiosoitteesi (pakollinen)"
  emailSubject = "Aihe"
  emailMessage = "Viestisi sisältö"
  send = "Lähetä"

  [Languages.fi.jumbotron]
  # These are the buttons right under the header that appears on the main page.
  # You can use them to link to a mailing list or Facebook page.
  # Make sure the links start with http:// or https://
  firstButtonLink = "https://www.facebook.com/EffectiveAltruismHY/"
  firstButtonText = "Facebook"
  secondButtonText = "Ota yhteyttä"
  secondButtonLink = "https://oaarne.github.io/lean-site-template/contact/"
  # Remove the # before the text to add the optional Meetup button
  # meetupButtonText = "Find us on Meetup"

  [Languages.fi.urls]
  ## -- EA GROUP FB/TWITTER/MEETUP URLS -- ##
  # If your group does not have URLs for these, just add # before the line
  # to remove the link from the site
  facebookUrl = "https://www.facebook.com/EffectiveAltruismHY/"
  # twitterUrl = ""
  # meetupUrl = ""
