baseURL = "https://rtcharity.github.io/lean-site-template/"
theme = "local-ea-template"

# If you are using multiple languages and want a different default,
# you can change this language code. In this particular case,
# baseURL will be th english site, and baseURL/<language code> will be the
# other languages.
DefaultContentLanguage = "en"

# These params are used by the local EA Hugo template
# used to generate the site. You can find the template
# at https://github.com/rtcharity/local-ea-template.
  [params]

  [Languages]
  [Languages.en]
  title = "Local EA Website"
  weight = 1
  languageCode = "en"

  [Languages.en.general]
  ## -- GENERAL SITE PARAMETERS -- ##
  fullTitle = "Effective Altruism Site Title"
  strapline = "Helping you do good better"

  ## -- EA GROUP INFO -- ##
  [Languages.en.groupinfo]
  legalOrgName = "Effective Altruism <City Here>"
  orgLocations = "this location and that location"
  contactEmail = "yourEAGroupEmail@here.com"

  [Languages.en.navbar]
  ## -- NAVIGATION BAR HEADERS -- ##
  # You probably don't need/want to change these,
  # but if you do you'll also want to change the relevant .md file under the
  # content folder so the copy corresponds with the header.
  home = "Home"
  faq = "FAQ"
  effectiveAltruism = "Effective Altruism"
  aboutEA = "About EA"
  readingMaterial = "Reading Material"
  keyTerms = "Key Terms"
  organizations = "Organizations"
  contact= "Contact"

  [Languages.en.pages]
  ## -- Page Headers -- ##
  contactPageHeader = "Contact us"
  aboutEAPageHeader = "What is Effective Altruism?"

  [Languages.en.homepage]
   ## -- HOMEPAGE -- ##
  topBannerText = "Who are we?"
  leadText = "We're a group of people who want to help you answer the question: how can I do good better?"
  firstSectionHeader = "Doing good better"
  secondSectionHeader = "Building a community"
  thirdSectionHeader = "Finding better ways to help"
  bottomBannerText = "A proud member of the effective altruism network"

  [Languages.en.contactform]
  leadText = "Say hi!"
  senderName = "Your name (required)"
  senderEmail = "Your email (required)"
  emailSubject = "Subject"
  emailMessage = "Your Message"
  send = "Send"

  [Languages.en.jumbotron]
  # These are the buttons right under the header that appears on the main page.
  # You can use them to link to a mailing list or Facebook page.
  # Make sure the links start with http:// or https://
  firstButtonText = "First Button Text"
  firstButtonLink = ""
  secondButtonText = "Second Button Text"
  secondButtonLink = ""
  # Remove the # before the text to add the optional Meetup button
  # meetupButtonText = "Find us on Meetup"

  [Languages.en.urls]
  ## -- EA GROUP FB/TWITTER/MEETUP URLS -- ##
  # If your group does not have URLs for these, just add # before the line
  # to remove the link from the site
  facebookUrl = ""
  twitterUrl = ""
  meetupUrl = ""
